<a href="https://colab.research.google.com/github/rmontteiro/Machine-Learning/blob/master/Desafio_Mod3_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd #biblioteca para manipulação de dados
import numpy as np #biblioteca para utilizacao de vetores e matrizes
import matplotlib.pyplot as plt #bibloteca para plotar graficos
import seaborn as sns
import datetime

In [2]:
#importando o nosso dataset
from google.colab import files
uploaded = files.upload()

Saving bloodtransf.csv to bloodtransf.csv


In [3]:
df = pd.read_csv('bloodtransf.csv')

In [4]:
df.head()

V1  V2     V3  V4  Class
0   2  50  12500  98      2
1   0  13   3250  28      2
2   1  16   4000  35      2
3   2  20   5000  45      2
4   1  24   6000  77      1

In [9]:
#verificando o formato do dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   V1      748 non-null    int64
 1   V2      748 non-null    int64
 2   V3      748 non-null    int64
 3   V4      748 non-null    int64
 4   Class   748 non-null    int64
dtypes: int64(5)
memory usage: 29.3 KB


In [5]:
# Verificando o numero de amostras (linhas) e features (colunas) do dataset. 
print('Amostras e Features:', df.shape)

Amostras e Features: (748, 5)


In [6]:
#contando valores nulos 
df.isnull().sum()

V1       0
V2       0
V3       0
V4       0
Class    0
dtype: int64

In [11]:
# armazenando os labels em um array
labels = np.array(df['Class'])

# salvando a ordem das features
feature_list = list(df.columns)

In [12]:

# Verificando quais são os tipos das features
df.columns

Index(['V1', 'V2', 'V3', 'V4', 'Class'], dtype='object')

In [13]:
# Analisando o resumo da base
df.describe()

V1          V2            V3          V4       Class
count  748.000000  748.000000    748.000000  748.000000  748.000000
mean     9.506684    5.514706   1378.676471   34.282086    1.237968
std      8.095396    5.839307   1459.826781   24.376714    0.426124
min      0.000000    1.000000    250.000000    2.000000    1.000000
25%      2.750000    2.000000    500.000000   16.000000    1.000000
50%      7.000000    4.000000   1000.000000   28.000000    1.000000
75%     14.000000    7.000000   1750.000000   50.000000    1.000000
max     74.000000   50.000000  12500.000000   98.000000    2.000000

In [14]:
# armazenando os labels em um array
labels = np.array(df['Class'])

# salvando a ordem das features
feature_list = list(df.columns)

In [16]:
# removendo a coluna de labels do df original
df2 = df.drop('Class', axis = 1)

# check
df2.columns

Index(['V1', 'V2', 'V3', 'V4'], dtype='object')

In [17]:
# convertendo df para array
data = np.array(df2)

In [18]:
# importar train_test_split do scikitlearn 
from sklearn.model_selection import train_test_split

# aplicando a funcao train_test_split para separar os conjuntos de treino e 
# teste segundo uma porcentagem de separação definida. 
train_data, test_data, train_labels, test_labels = train_test_split(data, labels, test_size = 0.25, random_state = 42)

In [19]:
# criando baseline
baseline_preds = np.random.choice([0,1], size = len(test_labels))

print(baseline_preds)

[0 1 0 1 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 1 1 0 1 0 0
 1 0 0 0 0 0 0 1 0 1 0 0 1 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 1 1 0 1 1 1 1 0 0
 1 0 0 0 1 0 0 1 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 1 1 1 0 0 1 1 0 0 0 0 0
 0 0 1 1 1 0 0 0 1 0 0 1 1 1 0 1 0 0 1 0 1 0 0 1 1 1 0 1 1 0 0 0 1 1 1 0 1
 1 0 1 0 1 1 0 0 0 1 1 1 0 0 0 1 1 1 1 1 1 0 0 1 0 1 0 1 1 1 0 1 1 0 0 0 0
 1 1]


In [20]:
from sklearn import metrics  

# calculando medidas de erro
# essas medidas são calculadas a partir da comparação com o valor real do nosso conjunto de teste
print('Matriz de Confusão\n', metrics.confusion_matrix(test_labels, baseline_preds)) 
print('\nAcurácia\n', metrics.accuracy_score(test_labels, baseline_preds)) 
print('\nAcurácia Balanceada por classe\n', metrics.balanced_accuracy_score(test_labels, baseline_preds)) 
print('\nPrecision\n', metrics.precision_score(test_labels, baseline_preds)) 
print('\nRecall\n', metrics.recall_score(test_labels, baseline_preds)) 
print('\nF1\n', metrics.f1_score(test_labels, baseline_preds)) 

print('\nAUCROC\n', metrics.roc_auc_score(test_labels, baseline_preds))

Matriz de Confusão
 [[ 0  0  0]
 [74 65  0]
 [30 18  0]]

Acurácia
 0.34759358288770054

Acurácia Balanceada por classe
 0.23381294964028776


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1859: UserWarning: y_pred contains classes not in y_true
  warnings.warn('y_pred contains classes not in y_true')


ValueError: ignored

In [21]:
#importar o modelo SVM
from sklearn.svm import SVC

# instanciacao e determinacao dos hiperparâmetros do SVM: tipo de kernel
classifier = SVC(kernel='rbf')

# treinando o SVM
classifier.fit(train_data,train_labels)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [22]:
# aplicando o modelo treinado para a previsão da temperatura 
#em todo o conjunto de teste
predictions2_labels = classifier.predict(test_data)

# Exibindo dataframe com valores 10 reais e suas respectivas previsões
p = pd.DataFrame({'Real': test_labels, 'Previsto': predictions2_labels})  
p.head(10)

Real  Previsto
0     1         1
1     1         1
2     1         1
3     1         1
4     1         1
5     1         1
6     1         1
7     1         1
8     1         1
9     1         1

In [23]:
#avaliando o modelo 
print('Matriz de Confusão\n', metrics.confusion_matrix(test_labels, predictions2_labels)) 
print('\nAcurácia\n', metrics.accuracy_score(test_labels, predictions2_labels)) 
print('\nAcurácia Balanceada por classe\n', metrics.balanced_accuracy_score(test_labels, predictions2_labels)) 
print('\nPrecision\n', metrics.precision_score(test_labels, predictions2_labels)) 
print('\nRecall\n', metrics.recall_score(test_labels, predictions2_labels)) 
print('\nF1\n', metrics.f1_score(test_labels, predictions2_labels)) 

print('\nAUCROC\n', metrics.roc_auc_score(test_labels, predictions2_labels))

Matriz de Confusão
 [[139   0]
 [ 47   1]]

Acurácia
 0.7486631016042781

Acurácia Balanceada por classe
 0.5104166666666666

Precision
 0.7473118279569892

Recall
 1.0

F1
 0.8553846153846154

AUCROC
 0.5104166666666666
